@echo off
echo Starting Backend Server...
start cmd /k "cd server && npm run dev"
echo Starting Frontend Server...
start cmd /k "cd client && npm start"
echo Both servers are starting...
echo Backend will be available at: http://localhost:5000
echo Frontend will be available at: http://localhost:3000
echo.
echo Press any key to close this window...
pause > nul